In [10]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

print("Libraries imported successfully!")

Libraries imported successfully!

In [12]:
df = pd.read_csv(r"C:\Users\shant\Python\customer-retention-system\data\raw\online_retail_II.csv", encoding="ISO-8859-1")

In [13]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.00,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.00,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.00,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.00,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.00,United Kingdom

In [14]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 541910
Columns: 8

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  object
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [16]:
df.describe(include="all")

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,541910,541910,540456,541910.00,541910,541910.00,406830.00,541910
unique,25900,4070,4223,NaN,23260,NaN,NaN,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/11 14:41,NaN,NaN,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,NaN,NaN,NaN,9.55,NaN,4.61,15287.68,NaN
std,NaN,NaN,NaN,218.08,NaN,96.76,1713.60,NaN
min,NaN,NaN,NaN,-80995.00,NaN,-11062.06,12346.00,NaN
25%,NaN,NaN,NaN,1.00,NaN,1.25,13953.00,NaN
50%,NaN,NaN,NaN,3.00,NaN,2.08,15152.00,NaN
75%,NaN,NaN,NaN,10.00,NaN,4.13,16791.00,NaN
max,NaN,NaN,NaN,80995.00,NaN,38970.00,18287.00,NaN

In [17]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [18]:
df.duplicated().sum()

5268

In [19]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [21]:
df.dtypes

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

In [22]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[ns]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [24]:
print("Start Date :", df["InvoiceDate"].min())
print("End Date   :", df["InvoiceDate"].max())

Start Date : 2010-12-01 08:26:00
End Date   : 2011-12-09 12:50:00

In [25]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean() * 100, 2)
})

missing.sort_values("Percentage", ascending=False)

             Missing Values  Percentage
Customer ID          135080       24.93
Description            1454        0.27
Invoice                   0        0.00
StockCode                 0        0.00
Quantity                  0        0.00
InvoiceDate               0        0.00
Price                     0        0.00
Country                   0        0.00

In [26]:
df.nunique().sort_values(ascending=False)

Invoice        25900
InvoiceDate    23260
Customer ID     4372
Description     4223
StockCode       4070
Price           1630
Quantity         722
Country           38
dtype: int64

In [27]:
df.memory_usage(deep=True)

Index               132
Invoice        34149621
StockCode      33645481
Description    45253059
Quantity        4335280
InvoiceDate     4335280
Price           4335280
Customer ID     4335280
Country        38137561
dtype: int64

In [28]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")

Memory Usage: 160.72 MB

In [29]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 5268

In [30]:
df[df["Quantity"] < 0].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.00,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.00,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.00,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.00,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.00,United Kingdom

In [31]:
(df["Quantity"] < 0).sum()

10624

In [32]:
df[df["Price"] == 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1510,536545,21134,NaN,1,2010-12-01 14:32:00,0.00,NaN,United Kingdom
1985,536547,37509,NaN,1,2010-12-01 14:33:00,0.00,NaN,United Kingdom
1986,536546,22145,NaN,1,2010-12-01 14:33:00,0.00,NaN,United Kingdom
2022,536552,20950,NaN,1,2010-12-01 14:34:00,0.00,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.00,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.00,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.00,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.00,NaN,United Kingdom
538925,581422,23169,smashed,-235,2011-12-08 15:24:00,0.00,NaN,United Kingdom

In [33]:
df["Country"].value_counts()

United Kingdom          495478
Germany                   9495
France                    8558
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: Country, dtype: int64

In [35]:
df["Customer ID"].nunique()

4372

In [36]:
df["StockCode"].nunique()

4070

In [37]:
df["Country"].nunique()

38

In [39]:
df.to_csv("../data/processed/data_understanding.csv", index=False)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[ns]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [41]:
df.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country']